name = "Quickbb"
uuid = "c15d73b8-6037-4296-b65f-d2ed8ab24eb2"
authors = ["John Brennan <john.brennan@ichec.ie> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
